keybinding:
  universal:
    return: '<c-q>'

gui:
  theme:
    selectedLineBgColor:
      - undeline
    selectedRangeBgColor:
      - undeline

git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
